name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    # - name: Start MLflow Tracking Server
    #   run: mlflow ui &

    # - name: Wait for MLflow Tracking Server to Start
    #   run: sleep 10s
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build Docker image
      run: |
        docker build -t streamlit_mrm .
        docker images

    - name: tag your image
      run: docker tag streamlit_mrm vikash2020/streamlit_mrm
    # - name: Wait for MLflow Tracking Server to Shut Down
    #   run: sleep 10s
    - name: Push Docker image to Docker Hub
      run: docker push vikash2020/streamlit_mrm

    - name: Run Docker container
      run: |
        docker run -d -p 8501:8501 vikash2020/streamlit_mrm:latest
    - name: Wait for the Streamlit app to start
      run: sleep 10s

    - name: Check if the app is running
      run: docker ps | grep vikash2020/streamlit_mrm

    - name: Open the Streamlit app in the browser
      run: |
        # Get the IP address of the running container
        CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))
        echo "Streamlit app is available at http://$CONTAINER_IP:8501"
